### ISSUE TITLE
es and forecast not working properly

### ISSUE THREAD

**Issue by xiesong** [config-i1/smooth#105] opened 2018-01-26 14:33 UTC
I'm using forecast package v. 8.3 and Smooth 2.3.1. When I run the following code, I get error and cannot plot forecast. Below is a reproducible example.

> x <- rpois(100,0.2)
> ourModel <- es(x,"ZZN",intermittent="auto")
Only additive models are allowed with the negative data.
Forming the pool of models based on... ANN, AAN, Estimation progress: 100%... Done! 
Time elapsed: 0.3 seconds
Model estimated: ETS(ANN)
Persistence vector g: 0
1 initial state was estimated in the process
Residuals standard deviation: 0.494
Cost function type: MSE; Cost function value: 0

Information criteria:
     AIC     AICc      BIC 
145.8604 146.1104 153.6759 

> forecast(ourModel)
Error in ets(object, lambda = lambda, allow.multiplicative.trend = allow.multiplicative.trend,  : 
  y should be a univariate time series
> plot(forecast(ourModel))
Error in ets(object, lambda = lambda, allow.multiplicative.trend = allow.multiplicative.trend,  : 
  y should be a univariate time series

**Comment by config-i1** [comment] 2018-01-26 18:45
Hi!
I've tried reproducing the error on the latest version of smooth (from github) but failed. Maybe that was one of those bugs, fixed in a recent update. Please, install the smooth from github and let me know if the bug persists. The code for the installation:
> devtools::install_github("config-i1/smooth")

**Comment by config-i1** [comment] 2018-01-29 11:31
Taking that there is no response and I cannot reproduce the error, I assume that the bug is fixed.

**Closed by config-i1** 2018-01-29 11:31 UTC

**Comment by xiesong** [comment] 2018-02-01 16:02
sorry for delayed response, the bug is fixed with updated version of R and smooth, thnak you for wonderful package.
