### ISSUE TITLE
Use ggplot2 to plot forecast of es()

### ISSUE THREAD

**Issue by andreykirson** [config-i1/smooth#117] opened 2018-05-24 10:15 UTC
Can and how to use the ggplot2 package to plot a forecast of es()?

**Comment by config-i1** [comment] 2018-05-24 10:20
I don't know. ggplot2 is external package, smooth does not depend on it. So I would recommend reading the manuals of ggplot2.

This is not a bug or a request of a feature for smooth, so I close this issue.

**Closed by config-i1** 2018-05-24 10:20 UTC
Labels: invalid
