### ISSUE TITLE
Error in match.names(clabs, names(xi))

### ISSUE THREAD

**Issue by Steviey** [config-i1/smooth#196] opened 2022-02-07 14:11 UTC
**_Windows 7, greybox 1.0.5.41001, smooth 3.1.6.41004, R version 4.0.5_**
Using this code I get the following error....

```
Sys.setenv(LANG = "en")
options(scipen = 999)
options(dplyr.summarise.inform=F)
options(max.print=2000) 
library("Hmisc")
suppressPackageStartupMessages(library(digest))
suppressPackageStartupMessages(library(lightgbm))
suppressPackageStartupMessages(library(digest))
suppressPackageStartupMessages(library(RSQLite))
suppressPackageStartupMessages(library(stringr))
suppressPackageStartupMessages(library(tidyr))
suppressPackageStartupMessages(library(dbplyr))
suppressPackageStartupMessages(library(rlang))
suppressPackageStartupMessages(library(freqdist))
suppressPackageStartupMessages(library(tidymodels))
options(tidymodels.dark = TRUE)
suppressPackageStartupMessages(library(modeltime))
suppressPackageStartupMessages(library(modeltime.ensemble))
suppressPackageStartupMessages(library(modeltime.resample))
suppressPackageStartupMessages(library(timetk))
suppressPackageStartupMessages(library(tidyverse)) 
suppressPackageStartupMessages(library(rsample)) 
suppressPackageStartupMessages(library(tidyquant))
suppressPackageStartupMessages(library(tibbletime))
suppressPackageStartupMessages(library(anomalize))
suppressPackageStartupMessages(library(smooth))
suppressPackageStartupMessages(library(lmtest))
suppressPackageStartupMessages(library(mgcv))
suppressPackageStartupMessages(library(fable))
suppressPackageStartupMessages(library(fabletools))
suppressPackageStartupMessages(library(tsibble))
suppressPackageStartupMessages(library(tsibbledata))
suppressPackageStartupMessages(library(tsfeatures))
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(ggrepel))
suppressPackageStartupMessages(library(runner))
suppressPackageStartupMessages(library(ggformula))
suppressPackageStartupMessages(library(fANCOVA))
suppressPackageStartupMessages(library(stats))
suppressPackageStartupMessages(library(TTR))
suppressPackageStartupMessages(library(xts))
suppressPackageStartupMessages(library(vip))
suppressPackageStartupMessages(library(yardstick))
suppressPackageStartupMessages(library(plotly))
suppressPackageStartupMessages(library(catboost))
suppressPackageStartupMessages(library(treesnip))
suppressPackageStartupMessages(library(broom))
suppressPackageStartupMessages(library(finetune))
suppressPackageStartupMessages(library(tabnet))
suppressPackageStartupMessages(library(lobstr))
suppressPackageStartupMessages(library(forecast))
options(error=function(){lobstr::cst();traceback(max.lines=1)})

liveData<-0
if(liveData<1){

    idx=120
    y<-rnorm(idx, mean=15, sd=5)
    x<-cbind(
        x1 =  rnorm(idx, mean=15, sd=5)
        ,x2 =  rnorm(idx, mean=15, sd=5)
        ,x3 =  rnorm(idx, mean=15, sd=5)
        ,x4 =  rnorm(idx, mean=15, sd=5)
        ,x5 =  rnorm(idx, mean=15, sd=5)
    )   
    df    <- data.frame(x=x,value=y,stringsAsFactors=F)
    df    <- df %>% dplyr::relocate(value)
}

rownames(df) <- NULL
df      <-  df %>% dplyr::mutate(id=row_number()) %>% relocate(id)
myH<-1
myLimit      <- as.numeric(nrow(df)-myH)
trainOneStep <- df %>% filter(id <= myLimit)
testOneStep  <- df %>% filter(id > myLimit)

View(trainOneStep)
View(testOneStep)

myModel <- adam(trainOneStep,"ANN",silent=TRUE,h=1,holdout=FALSE)

# #myPlot<-plot(forecast::forecast(myModel,h=10,interval="complete",nsim=100),main="Complete prediction interval")
#myPlot<-plot(generics::forecast(myModel,newdata=testOneStep,interval="complete",nsim=100),main="Complete prediction interval")
myPlot<-plot(generics::forecast(myModel,newdata=testOneStep, interval="prediction", level=c(0.9,0.95)))

print(myPlot)

Error in match.names(clabs, names(xi)) : 
  names do not match previous names
In addition: Warning message:
The newdata has 1 observations, while 10 are needed. Using the last available values as future ones. 
    x
 1. +-base::plot(...) at R/PslTools/dummy.R:824:0
 2. +-generics::forecast(...) at R/PslTools/dummy.R:824:0
 3. +-smooth:::forecast.adam(...)
 4. | \-base::rbind(...)
 5. |   \-base::rbind(deparse.level, ...)
 6. |     \-base match.names(clabs, names(xi))
 7. |       \-base::stop("names do not match previous names")
 8. \-global `<fn>`()
 9.   \-lobstr::cst() at R/PslTools/dummy.R:55:25
13: stop("names do not match previous names")
12: match.names(clabs, names(xi))
11: rbind(deparse.level, ...)
10: rbind(newdata, matrix(rep(tail(newdata, 1), each = newnRows), 
     ...
9: reforecast.adam(object, h = h, newdata = newdata, occurrence = occurrence, 
    ...
8: reforecast(object, h = h, newdata = newdata, occurrence = occurrence, 
    ...
7: forecast.adam(myModel, newdata = testOneStep, interval = "complete", 
    ...
6: generics::forecast(myModel, newdata = testOneStep, interval = "complete", 
    ... at dummy.R#823
5: plot(generics::forecast(myModel, newdata = testOneStep, interval = "complete", 
    ... at dummy.R#823
4: eval(ei, envir)
3: eval(ei, envir)
2: withVisible(eval(ei, envir))
```

**Comment by config-i1** [comment] 2022-02-07 15:14
Thanks for the bug report. This is not an intended behaviour, and I will fix this. In the meantime, please use "h=1" in forecast to resolve this.

**Comment by config-i1** [comment] 2022-02-07 15:30
Yes. This is because the newdata has 1 observation, while 10 are needed, and it tries using the last available values as future ones, but there is an issue with the bloody data.frame(). Fix is comming.

**Comment by config-i1** [comment] 2022-02-07 15:55
Fixed in 097674d9d0526c1f020bb80b8b0cd2142d916bd4

**Closed by config-i1** 2022-02-07 15:55 UTC
Labels: bug

**Comment by Steviey** [comment] 2022-02-07 16:33
The first test with tidymodels fails....

``
Error in eval(predvars, data, env) : object 'n2cat' not found
In addition: Warning message:
The newdata has 1 observations, while 10 are needed. Using the last available values as future ones. 
    x
 1. +-global pslPlotModel(...) at R/PslTools/dummy.R:939:12
 2. | +-generics::forecast(...) at R/PslTools/dummy.R:361:12
 3. | \-smooth:::forecast.adam(...)
 4. |   +-stats::model.frame(testFormula, data = xreg)
 5. |   \-stats::model.frame.default(testFormula, data = xreg)
 6. |     \-base::eval(predvars, data, env)
 7. |       \-base::eval(predvars, data, env)
 8. \-global `<fn>`()
 9.   \-lobstr::cst() at R/PslTools/dummy.R:53:25
No traceback available
``

Testing now native....

**Comment by config-i1** [comment] 2022-02-07 16:57
Yes, looks ridiculous (plus it overfits the data) :). But I'm glad you enjoy it.

**Comment by Steviey** [comment] 2022-02-07 16:57
... Looks better with...

myPlot<-plot(generics::forecast(myModel,newdata=testOneStep,h=nrow(testOneStep),interval="prediction", level=c(0.9,0.95)))

![image](https://user-images.githubusercontent.com/3146082/152834977-958c8fef-7fce-459f-8cfd-f5f5ad8449f3.png)

**Comment by Steviey** [comment] 2022-02-07 17:08
re overfitting: **This was without filtering recipes :-)**

**Comment by Steviey** [comment] 2022-02-07 17:40
model.frame.default(testFormula, data = xreg) ... hm hm :-)

**Comment by config-i1** [comment] 2022-02-07 17:42
If there is an error, please provide a short reproducible example, so that I can debug and fix.

**Comment by Steviey** [comment] 2022-02-07 18:13
From my point of view, there ist nothing native wrong.

**Comment by Steviey** [comment] 2022-02-08 07:11
Maybe I should investigate it a little deeper. Is there any direction you see adthoc?

```
+-global pslPlotModel(...) at R/PslTools/dummy.R:939:12
| +-generics::forecast(...) at R/PslTools/dummy.R:361:12
| -smooth:::forecast.adam(...)
| +-stats::model.frame(testFormula, data = xreg)
| -stats::model.frame.default(testFormula, data = xreg)
| -base::eval(predvars, data, env)
| -base::eval(predvars, data, env)
-global <fn>()
-lobstr::cst() at R/PslTools/dummy.R:53:25
No traceback available

```

**Comment by config-i1** [comment] 2022-02-08 12:45
So, I don't know what happens here and why. `model.frame()` is used to expand the data.frame into a matrix. If you cannot reproduce this on a small example, then just make sure that you follow this:

1. Number of rows in the `newdata` that you provide to forecast function should be equal to the forecast horizon. Otherwise the function will substitute it with something else.
2. Make sure that the `newdata` has exactly the same set of variables as the `data` used in adam(), with exactly the same names of variables.
3. If you do not use `formula` in adam, then function will use formula `y~.`, substituting `y` with the name of your variable. This typically works fine, but you can also try writing the formula explicitly.

Hope this helps.

**Comment by config-i1** [comment] 2022-02-09 17:46
The most efficient way is `h=nrow(data)`. Because otherwise function will try fixing the length, and it won't not necessarily be correct. You have explanatory for a reason. You can either control them (prices, promotions) or predict them to some extent (weather). It's better to provide future values than to let it deal with it on its own.

**Comment by Steviey** [comment] 2022-02-09 23:49
Thank you, I will do it a little later. There is much hidden stuff in there (modeltime.ensemble).
